<a href="https://colab.research.google.com/github/Nagasri1224/2303A52456_Gene_Ai/blob/main/2303A52456_Gene_Ai_As1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
ya=[10,20,30,40,50]

In [2]:
yp=[10.2,20.5,30.3,40.8,50.6]

In [4]:
sum=0
for i in range(len(ya)):
    sum=sum+(ya[i]-yp[i])**2

In [5]:
sum/len(ya)

0.27599999999999947

In [6]:
import numpy as np

In [7]:
sum=0
for i in range(len(ya)):
  sum=sum+np.abs((ya[i]-yp[i]))

In [8]:
sum/len(ya)

0.4799999999999997

In [9]:
sum=0
for i in range(len(ya)):
  sum=sum+(ya[i]-yp[i])**2

In [10]:
np.sqrt((sum/len(ya)))

0.5253570214625474

In [11]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,root_mean_squared_error
print(mean_squared_error(ya,yp))
print(mean_absolute_error(ya,yp))
print(root_mean_squared_error(ya,yp))

0.27599999999999947
0.4799999999999997
0.5253570214625474


In [13]:
ya1=[0,0,0,0,0,1,1,1,1,1,1,2,2,2,2,2]
yp1=[0,0,1,1,2,2,0,1,1,1,2,0,2,1,1,2]

In [14]:
count=0
for i in range(len(ya1)):
  if(ya1[i]==yp1[i]):
    count=count+1

In [15]:
(count/len(ya1))*100

43.75

In [17]:
from sklearn.metrics import accuracy_score
print(accuracy_score(ya1,yp1))

0.4375


In [18]:
A=[[0,0,0],[0,0,0],[0,0,0]]

In [19]:
A=np.array(A)

In [20]:
for i in range(len(ya1)):
  if(ya1[i]==yp1[i]):
    A[ya1[i]][yp1[i]]=A[ya1[i]][yp1[i]]+1

  else:
    A[ya1[i]][yp1[i]]=A[ya1[i]][yp1[i]]+1


In [21]:
A

array([[2, 2, 1],
       [1, 3, 2],
       [1, 2, 2]])

In [22]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(ya1,yp1))

[[2 2 1]
 [1 3 2]
 [1 2 2]]
